# =============================================================
# DOODLY — Static site generator
# Reads the route table from assets/js/manifest.js and stamps one
# self-contained HTML page per route. Each page is an identical
# shell (data-route + <title>); layout.js renders the chrome and
# the route's block recipe at runtime. Re-run after adding routes.
#
#   powershell -ExecutionPolicy Bypass -File tools/generate.ps1
# =============================================================
param([string]$Root = (Split-Path $PSScriptRoot -Parent))

$manifestPath = Join-Path $Root 'assets/js/manifest.js'
if (-not (Test-Path $manifestPath)) { throw "manifest.js not found at $manifestPath" }
$manifest = Get-Content $manifestPath -Raw

# Each route object begins:  "route/key": { surface:"x", title:"y"
$rx = [regex]'"(?<route>[^"]+)":\s*\{\s*surface:"(?<surface>[^"]+)",\s*title:"(?<title>(?:[^"\\]|\\.)*)"'

$template = @'
<!doctype html>
<html lang="en" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{TITLE}} &middot; DOODLY</title>
  <meta name="description" content="{{DESC}}">{{HEAD_EXTRA}}
  <meta name="theme-color" content="#0F3D2E">
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><rect width='64' height='64' rx='18' fill='%231FAE66'/><g fill='none' stroke='white' stroke-width='6'><circle cx='26' cy='32' r='11'/><circle cx='42' cy='32' r='11'/></g></svg>">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400..700;1,9..144,400..600&family=Hanken+Grotesk:wght@400;500;600;700;800&display=swap" media="print" onload="this.media='all'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400..700;1,9..144,400..600&family=Hanken+Grotesk:wght@400;500;600;700;800&display=swap"></noscript>
  <!-- All ~37 stylesheets concatenated (in cascade order) into one bundle by tools/minify.mjs -->
  <link rel="stylesheet" href="/assets/css/bundle.min.css">
</head>
<body data-route="{{ROUTE}}">
  <!-- This file is generated by tools/generate.ps1 — do not edit by hand.
       Content lives in assets/js/manifest.js (recipe) + blocks.js (renderers). -->
  <div id="root"><div class="boot"><div class="ripple"><span></span><i></i><i></i></div><div class="boot-word">DOODLY</div></div></div>
  <script src="/assets/js/data.min.js"></script>
  <script src="/assets/js/analytics.min.js"></script>
  <script src="/assets/js/api.min.js"></script>
  <script src="/assets/js/catalogue.min.js"></script>
  <script src="/assets/js/cms.min.js"></script>
  <script src="/assets/js/status.min.js"></script>
  <script src="/assets/js/schedule.min.js"></script>
  <script src="/assets/js/pincode.min.js"></script>
  <script src="/assets/js/autopay.min.js"></script>
  <script src="/assets/js/maps.min.js"></script>
  <script src="/assets/js/rbac.min.js"></script>
  <script src="/assets/js/mockdata.min.js"></script>
  <script src="/assets/js/blocks.min.js"></script>
  <script src="/assets/js/datatable.min.js"></script>
  <script src="/assets/js/manifest.min.js"></script>
  <script src="/assets/js/builder.min.js"></script>
  <script src="/assets/js/motion.min.js"></script>
  <script src="/assets/js/quickbuy.min.js"></script>
  <script src="/assets/js/variant-select.min.js"></script>
  <script src="/assets/js/cart.min.js"></script>
  <script src="/assets/js/checkout.min.js"></script>
  <script src="/assets/js/exit-intent.min.js"></script>
  <script src="/assets/js/auth.min.js"></script>
  <script src="/assets/js/qr.min.js"></script>
  <script src="/assets/js/unfold.min.js"></script>
  <script src="/assets/js/wallet.min.js"></script>
  <script src="/assets/js/referral.min.js"></script>
  <script src="/assets/js/invoice.min.js"></script>
  <script src="/assets/js/assistant.min.js"></script>
  <script src="/assets/js/customer.min.js"></script>
  <script src="/assets/js/liveorder.min.js"></script>
  <script src="/assets/js/help.min.js"></script>
  <script src="/assets/js/tour.min.js"></script>
  <script src="/assets/js/search.min.js"></script>
  <script src="/assets/js/puzzle.min.js"></script>
  <script src="/assets/js/loyalty.min.js"></script>
  <script src="/assets/js/reviews.min.js"></script>
  <script src="/assets/js/rewards.min.js"></script>
  <script src="/assets/js/account.min.js"></script>
{{ADMIN_SCRIPTS}}  <script src="/assets/js/layout.min.js"></script>
</body>
</html>
'@

# Back-office-only scripts (~550KB). Emitted ONLY on admin/driver/delivery pages —
# the storefront (public/account/auth) never uses these, so shoppers stop downloading
# them. Each self-gates to /admin/ or /driver/ (or has no customer route), verified.
$adminScripts = @'
  <script src="/assets/js/delivery.min.js"></script>
  <script src="/assets/js/rbac-admin.min.js"></script>
  <script src="/assets/js/audit.min.js"></script>
  <script src="/assets/js/admin-cms.min.js"></script>
  <script src="/assets/js/expenses.min.js"></script>
  <script src="/assets/js/b2b.min.js"></script>
  <script src="/assets/js/b2b-pricing.min.js"></script>
  <script src="/assets/js/dashboard.min.js"></script>
  <script src="/assets/js/late.min.js"></script>
  <script src="/assets/js/employees.min.js"></script>
  <script src="/assets/js/assign.min.js"></script>
  <script src="/assets/js/gst.min.js"></script>
  <script src="/assets/js/rewards-admin.min.js"></script>
'@
$adminSurfaces = @('admin', 'driver', 'delivery')

# Default meta description (unchanged pages keep this byte-for-byte).
$defaultDesc = 'DOODLY — fresh A2 buffalo milk, delivered daily in glass bottles.'
# Per-route rich SEO / social-share metadata. Routes NOT listed here render the
# generic head exactly as before (no diff). Add a route to give it OG + Twitter
# cards, a canonical URL and JSON-LD structured data.
$seo = @{
  'check-delivery' = @{
    desc      = 'Fresh A2 buffalo milk delivered to your doorstep. Check if DOODLY delivers to your area in seconds — glass bottles, at your door before 7 AM.'
    ogTitle   = 'DOODLY — Check Delivery Availability'
    image     = 'https://doodly.in/assets/img/products/milk-lifestyle.jpg'
    canonical = 'https://doodly.in/check-delivery'
  }
}
# Routes that must never be indexed (private, token-gated pages).
$noindexRoutes = @('rewards/claim')
function Build-HeadExtra($s) {
  $ld = '{"@context":"https://schema.org","@type":"WebPage","name":"' + $s.ogTitle + '","description":"' + $s.desc + '","url":"' + $s.canonical + '","publisher":{"@type":"Organization","name":"DOODLY","logo":"https://doodly.in/assets/img/logo.png"}}'
  $lines = @(
    "  <link rel=""canonical"" href=""$($s.canonical)"">",
    "  <meta property=""og:type"" content=""website"">",
    "  <meta property=""og:site_name"" content=""DOODLY"">",
    "  <meta property=""og:title"" content=""$($s.ogTitle)"">",
    "  <meta property=""og:description"" content=""$($s.desc)"">",
    "  <meta property=""og:url"" content=""$($s.canonical)"">",
    "  <meta property=""og:image"" content=""$($s.image)"">",
    "  <meta property=""og:image:width"" content=""1200"">",
    "  <meta property=""og:image:height"" content=""630"">",
    "  <meta name=""twitter:card"" content=""summary_large_image"">",
    "  <meta name=""twitter:title"" content=""$($s.ogTitle)"">",
    "  <meta name=""twitter:description"" content=""$($s.desc)"">",
    "  <meta name=""twitter:image"" content=""$($s.image)"">",
    "  <script type=""application/ld+json"">$ld</script>"
  )
  return "`n" + ($lines -join "`n")
}

# Refresh the minified JS artifacts (assets/js/*.min.js) the pages reference.
# Resilient: minify.mjs exits 0 (keeping existing committed .min.js) if node/terser is absent.
try { & node (Join-Path $Root 'tools/minify.mjs') } catch { Write-Host "  (minify skipped: $_)" -ForegroundColor Yellow }

# Content-hash build id → stamped as ?v=<id> on every .min.js/.min.css URL so those
# assets are safely immutable-long-cacheable (the URL changes only when content changes).
$buildId = ''
try { $buildId = (Get-Content (Join-Path $Root 'assets/build-id.txt') -Raw).Trim() } catch { }

$utf8 = New-Object System.Text.UTF8Encoding($false)
$count = 0
$bySurface = @{}

foreach ($m in $rx.Matches($manifest)) {
  $route   = $m.Groups['route'].Value
  $title   = $m.Groups['title'].Value
  $surface = $m.Groups['surface'].Value
  $file    = if ($route -eq 'home') { 'index.html' } else { "$route.html" }
  $path    = Join-Path $Root $file
  $dir     = Split-Path $path -Parent
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

  $desc = $defaultDesc
  $headExtra = ''
  if ($noindexRoutes -contains $route) { $headExtra = "`n  <meta name=""robots"" content=""noindex, nofollow"">" }
  elseif ($seo.ContainsKey($route)) { $desc = $seo[$route].desc; $headExtra = Build-HeadExtra $seo[$route] }

  $adminBlock = if ($adminSurfaces -contains $surface) { $adminScripts + "`n" } else { '' }
  $html = $template.Replace('{{ROUTE}}', $route).Replace('{{TITLE}}', $title).Replace('{{DESC}}', $desc).Replace('{{HEAD_EXTRA}}', $headExtra).Replace('{{ADMIN_SCRIPTS}}', $adminBlock)
  if ($buildId) { $html = $html.Replace('.min.js"', ".min.js?v=$buildId`"").Replace('.min.css"', ".min.css?v=$buildId`"") }
  [System.IO.File]::WriteAllText($path, $html, $utf8)
  $count++
  if (-not $bySurface.ContainsKey($surface)) { $bySurface[$surface] = 0 }
  $bySurface[$surface]++
}

Write-Host "DOODLY - generated $count pages:" -ForegroundColor Green
$bySurface.GetEnumerator() | Sort-Object Name | ForEach-Object { Write-Host ("  {0,-9} {1}" -f $_.Key, $_.Value) }
